### ISSUE TITLE
Not working on Android 10 (API level 29)

### ISSUE THREAD

**Issue by hamzaydia** [lizizi/Hook_Start_Activity_Demo#1]
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lzy.plugintest/com.lzy.plugintest.MainActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.lzy.plugintest/com.lzy.plugintest.SecondActivity}; have you declared this activity in your AndroidManifest.xml?`

**Comment by lizizi** [comment]
After I read the source code, Android 10 related APIs are restricted and become private APIs of the framwork layer. At my current level, I ca n’t do it, I ’m sorry, so I ca n’t make it compatible with Android 10

**Comment by hamzaydia** [comment]
I think hidden API can be accessed with reflection something like:

https://github.com/ganyao114/SandHook/blob/master/hooklib/src/main/java/com/swift/sandhook/utils/ReflectionUtils.java

Me as well for my current level I can't do it, Thank you.
